[package]
name = "imgscale"
description = "A library for generating various sizes of an image and the appropriate html <img> tag"
categories = [
    "development-tools::build-utils",
    "web-programming",
    "multimedia::images"
]
license = "MIT OR Apache-2.0"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
readme.workspace = true

[features]
default = []
clap = ["dep:clap"] # Implement clap traits
zenwebp-agpl = ["dep:zenwebp"] # Use zenwebp as webp-backend (Note: `AGPL-3.0-only` licensed)

[dependencies]
clap = { version = "4", features = ["derive"], optional = true }
thiserror = "2"
image = { version = "0.25", default-features = false, features = [
    "png",
    "jpeg",
    "webp",
    "avif",
] }
zenwebp = { version = "0.4", optional = true }
