[package]
name = "imgscale-cli"
version = "0.1.0"
description = "A cli for generating various sizes of an image and the appropriate html <img> tag"
edition = "2024"
license = "AGPL-3.0-only"

[[bin]]
# Renames the bin to "imgscale", while keeping "cargo install imgscale-cli"
name = "imgscale"
path = "src/main.rs"

[dependencies]
imgscale = { path = "../imgscale", features = ["clap", "zenwebp-agpl"] }
clap = { version = "4.6", features = ["derive"] }
