[package]
name = "imgscale-cli"
description = "A cli for generating various sizes of an image and the appropriate html <img> tag"
categories = [
    "command-line-utilities",
    "development-tools::build-utils",
    "web-programming",
    "multimedia::images"
]
license = "AGPL-3.0-only"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
readme.workspace = true

[[bin]]
# Renames the bin to "imgscale", while keeping "cargo install imgscale-cli"
name = "imgscale"
path = "src/main.rs"

[dependencies]
imgscale = { path = "../imgscale", version = "0.2.1", features = ["clap", "zenwebp-agpl"] }
clap = { version = "4.6", features = ["derive"] }
